apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyaylawyer-deployment
  labels:
    app: nyaylawyer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nyaylawyer
  template:
    metadata:
      labels:
        app: nyaylawyer
    spec:
      containers:
      - name: nyaylawyer
        image: akhilbmenon/nyaylawyer.ai:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8502
        env:
        - name: PORT
          value: "8502"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        # Health Probes
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8502
          initialDelaySeconds: 1200
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8502
          initialDelaySeconds: 150
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: nyaylawyer-service
  labels:
    app: nyaylawyer
spec:
  selector:
    app: nyaylawyer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8502
      nodePort: 30010
  type: NodePort